version: '3.8'

services:
  gradio-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ${ECR_REGISTRY:-gradio-app}:${IMAGE_TAG:-latest}
    container_name: gradio-app
    ports:
      - "${PORT:-7860}:7860"
    environment:
      - GRADIO_SERVER_NAME=0.0.0.0
      - GRADIO_SERVER_PORT=7860
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    logging:
      driver: awslogs
      options:
        awslogs-group: ${AWS_LOGS_GROUP:-gradio-app}
        awslogs-region: ${AWS_REGION:-ap-northeast-1}
        awslogs-stream-prefix: gradio
